WebApplication5/Models/departement.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class departement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public departement()
        {
            this.equipement = new HashSet<equipement>();
        }
    
        public int id_dep { get; set; }
        public string libelledep { get; set; }
    
        public virtual eya eya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipement> equipement { get; set; }
    }
}

WebApplication5/Controllers/departementsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication5.Models;

namespace WebApplication5.Controllers
{
    public class departementsController : Controller
    {
        private NewdbEntities18 db = new NewdbEntities18();

        // GET: departements
        public ActionResult Homee()
        {
            return View(db.departement.ToList());
        }

        // GET: departements/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            departement departement = db.departement.Find(id);
            if (departement == null)
            {
                return HttpNotFound();
            }
            return View(departement);
        }

        // GET: departements/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: departements/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_dep,libelledep")] departement departement)
        {
            if (ModelState.IsValid)
            {
                db.departement.Add(departement);
                db.SaveChanges();
                return RedirectToAction("Homee");
            }

            return View(departement);
        }

        // GET: departements/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            departement departement = db.departement.Find(id);
            if (departement == null)
            {
                return HttpNotFound();
            }
            return View(departement);
        }

        // POST: departements/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_dep,libelledep")] departement departement)
        {
            if (ModelState.IsValid)
            {   
                db.Entry(departement).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Homee");
            }
            return View(departement);
        }

        // GET: departements/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            departement departement = db.departement.Find(id);
            if (departement == null)
            {
                return HttpNotFound();
            }
            return View(departement);
        }

        // POST: departements/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            departement departement = db.departement.Find(id);

            var l = from b in db.equipement
                    where b.id_dep == id
                    select b.id_equip;
            /*db.equipement.Select(id_equip).Where(x => x.id_dep == id).First();*/
            //db.equipement.Remove(l);
            //var p =db.demande.Where(x =>x.id_equip=={equipement.Select id_equip Where);
            foreach (var i in l)
            {
                var le =
                    from c in db.demande
                    where c.id_equip == i /*(from b in db.equipement where b.id_dep == id select b.id_equip;)*/
                    select c.id_demande;
                var lee =
                    from d in db.fiche_tech
                    where d.id_equip == i
                    select d.id_fiche;
                var o =
                    from k in db.intervention
                    where k.id_equip == i
                    select k.id_inter;
                foreach (var j in o)
                {
                    var y =
                    from k in db.piece
                    where k.id_inter == j
                    select k.id_piece;
                    foreach (var h in y)
                    {
                        piece p = db.piece.Find(h);
                        db.piece.Remove(p);
                    }
                    //db.SaveChanges();
                    intervention w = db.intervention.Find(j);
                    db.intervention.Remove(w);
                }

                //db.SaveChanges();
                foreach (var e in le)
                {
                    demande de = db.demande.Find(e);
                    db.demande.Remove(de);
                    //db.SaveChanges();
                }
                foreach (var ee in lee)
                {
                    fiche_tech f = db.fiche_tech.Find(ee);
                    db.fiche_tech.Remove(f);
                    //db.SaveChanges();
                }
                equipement eq = db.equipement.Find(i);
                db.equipement.Remove(eq);
                //db.SaveChanges();

            }
            db.SaveChanges();
            db.departement.Remove(departement);
            db.SaveChanges();
            return RedirectToAction("Homee");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication5/Views/departements/Create.cshtml
@model WebApplication5.Models.departement

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/mainten/_Layoutmainte.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>departement</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.libelledep, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.libelledep, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.libelledep, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Homee")
</div>

WebApplication5/Views/departements/Delete.cshtml
@model WebApplication5.Models.departement

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/mainten/_Layoutmainte.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>departement</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.libelledep)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.libelledep)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Homee")
        </div>
    }
</div>

WebApplication5/Views/departements/Details.cshtml
@model WebApplication5.Models.departement

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/mainten/_Layoutmainte.cshtml";
}

<h2>Details</h2>

<div>
    <h4>departement</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.libelledep)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.libelledep)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_dep }) 
    @Html.ActionLink("Back to List", "Homee")
</p>

WebApplication5/Views/departements/Edit.cshtml
@model WebApplication5.Models.departement

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/mainten/_Layoutmainte.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>departement</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_dep)

        <div class="form-group">
            @Html.LabelFor(model => model.libelledep, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.libelledep, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.libelledep, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Homee")
</div>

WebApplication5/Views/departements/Homee.cshtml
@model IEnumerable<WebApplication5.Models.departement>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/mainten/_Layoutmainte.cshtml";
}
<br />
<br />
<br />
<h2>Gestion des départements</h2>
<style>
    .active i{color :#0026ff;}
</style>
<p>
    @Html.ActionLink("Ajouter un département", "Create")
</p>
<table class="table table-bordered">
    <tr class="btn-primary">
        <th>
            @Html.DisplayNameFor(model => model.libelledep)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.libelledep)
        </td>
        <td>
           

            <li class="active"><a href="@Url.Action("Edit", "departements", new { id = item.id_dep })"><i class="fas fa-edit fa-2x"></i> </a>
            <a href="@Url.Action("Details", "departements",new { id = item.id_dep })"><i class="fas fa-info-circle fa-2x "></i></a>
             <a href="@Url.Action("Delete", "departements", new { id = item.id_dep })"><i class="fas fa-trash-alt fa-2x "></i></a>

            @*@Html.ActionLink("Edit", "Edit", new { id = item.id_dep }) |
            @Html.ActionLink("Details", "Details", new { id = item.id_dep }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.id_dep })*@
            @*<a href="@Url.Action("Delete", "departements")"><i class="fas fa-trash-alt fa-2x"></i></a>*@
            </li>
        </td>
    </tr>
}

</table>