WebApplication5/Controllers/maintenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using System.Net;
using WebApplication5.Models;
using System.Configuration;
using WebApplication5.ViewModel;
using System.Data.SqlClient;
using System.Data.Entity.Infrastructure;
using System.Threading.Tasks;
using System.Data.Entity.Validation;
using System.IO;

namespace WebApplication5.Controllers
{
    public class maintenController : Controller
    {
        public static List<clientdetails> listcl = new List<clientdetails>();
        NewdbEntities18 db = new NewdbEntities18();
        // GET: mainten
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult gestequip()
        {
            NewdbEntities18 db = new NewdbEntities18();
            List<maintdetails> maintD = new List<maintdetails>();

            //List<maintdetails> ObjFiles = new List<maintdetails>();
            //clientdetails cd = new clientdetails();
            var num = db.equipement.Select(a => a.id_equip).ToList();
            var dept = db.departement.Select(a => a.libelledep).ToList();
            var rf = db.equipement.Select(a => a.@ref).ToList();
            var lb = db.equipement.Select(a => a.libelleq).ToList();
            var tp = db.type.Select(a => a.denomination).ToList();
            var inter = db.type_entretien.Select(a => a.libellentr).ToList();
            var fic = db.fiche_tech.Select(a => a.fiche).ToList();
            var dt = db.intervention.Select(a => a.date_inter).ToList();
            foreach (int item in num)
            {
                maintdetails ab = new maintdetails();
                ab.Numéro = item;
                ab.Département = dept[item-1 ];
                ab.Référence = rf[item - 1];
                ab.Libellé = lb[item - 1];
                ab.Type = tp[item - 1];
                ab.Historique_de_réparation = (inter[item - 1]) + " : " + (dt[item - 1]);
                maintD.Add(ab);

            }
            ViewBag.Message = maintD;
            return View();

            //return View();
            //List<maintdetails> ObjFiles = new List<maintdetails> ();
            //foreach (string strfile in Directory.GetFiles(Server.MapPath("~/Files")))
            //{
            //    FileInfo fi = new FileInfo(strfile);
            //    maintdetails obj = new maintdetails();
            //    obj.File = fi.Name;
            //    obj.Size = fi.Length;
            //    obj.Type = GetFileTypeByExtension(fi.Extension);
            //    ObjFiles.Add(obj);
            //}
            //return View(ObjFiles);

        }
            [HttpPost]
            public ActionResult gestequip(HttpPostedFileBase file)
            {

            try
            {

                if (file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var filePath = Path.Combine(Server.MapPath("~/Files"), fileName);
                    file.SaveAs(filePath);

                }
                ViewBag.Message = "Uploaded Filed succeded";
                return RedirectToAction("gestequip");
            }

            catch
            {
                ViewBag.Message = "jkzdbcumiebzcehf";
                return RedirectToAction("Index");
            }

            //TempData["Message"] = "files uploaded successfully";
            //return RedirectToAction("Index");
        }
   


    //List<maintdetails> ObjFiles = new List<maintdetails>();
    //   foreach (string strfile in Directory.GetFiles(Server.MapPath("~/Files")))
    //   {
    //            FileInfo fi = new FileInfo(strfile);
    //            maintdetails obj = new maintdetails();
    //            obj.File = fi.Name;
    //            obj.Size = fi.Length;
    //            obj.Type = GetFileTypeByExtension(fi.Extension);
    //            ObjFiles.Add(obj);
    //   }

    //   return View(ObjFiles);
    //}
    //public FileResult Download(string fileName)
    //{
    //    string fullPath = Path.Combine(Server.MapPath("~/Files"), fileName);
    //    byte[] fileBytes = System.IO.File.ReadAllBytes(fullPath);
    //    return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
    //}
    //private string GetFileTypeByExtension(string fileExtension)
    //{
    //    switch (fileExtension.ToLower())
    //    {
    //        case ".docx":
    //        case ".doc":
    //            return "Microsoft Word Document";
    //        case ".xlsx":
    //        case ".xls":
    //            return "Microsoft Excel Document";
    //        case ".txt":
    //            return "Text Document";
    //        case ".jpg":
    //        case ".png":
    //            return "Image";
    //        default:
    //            return "Unknown";
    //    }
    //}
    //[HttpPost]
    //public ActionResult gestequip(maintdetails doc)
    //{
    //    NewdbEntities15 db = new NewdbEntities15();
    //    List<maintdetails> maintD = new List<maintdetails>();
    //    maintdetails ab = new maintdetails();
    //    fiche_tech fh = new fiche_tech();
    //    foreach (var file in doc.files)
    //    {
    //        if (file.ContentLength > 0)
    //        {
    //            var fileName = Path.GetFileName(file.FileName);
    //            var filePath = Path.Combine(Server.MapPath("~/Files"), fileName);
    //            file.SaveAs(filePath);
    //            fh.id_fiche = Int32.Parse(filePath);
    //            ab.Fiche_technique = filePath;
    //        }
    //    }
    //    //maintD.Add(ab);
    //    //ViewBag.Message = maintD;

    //    TempData["Message"] = "files uploaded successfully";
    //    return RedirectToAction("Index");
    //}
    public ActionResult Ajout()
        { return View(); }
        [HttpPost]
        public ActionResult Ajout(class2 cld)
        { 
                NewdbEntities18 db = new NewdbEntities18();
                departement dp = new departement();
                dp.id_dep = (int)cld.id_dep;
                dp.libelledep = cld.libelledep;
                db.departement.Add(dp);
                db.SaveChanges();
                type t = new type();
                t.id_type = (int)cld.id_type;
                t.denomination = cld.denomination;
                db.type.Add(t);
                db.SaveChanges();
                equipement eq = new equipement();
                eq.id_dep = cld.id_dep;
                eq.id_type = t.id_type;
                eq.id_equip = cld.id_equip;
                eq.libelleq = cld.libelleq;
                eq.@ref = cld.@ref;
                db.equipement.Add(eq);
                db.SaveChanges();
                fiche_tech fch = new fiche_tech();
                fch.id_fiche = cld.id_fiche;
                fch.id_equip = cld.id_equip;
                db.fiche_tech.Add(fch);
                db.SaveChanges();
                type_entretien tp = new type_entretien();
                int last = cld.id_typentr;
                tp.id_typentr = last;
                tp.libellentr = cld.libellentr;
                db.type_entretien.Add(tp);
                db.SaveChanges();
               
                return RedirectToAction("gestequip");
            }
        public ActionResult Edit(int? numé)
        {
            equipement e = db.equipement.Find(numé);
            return View(e);
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Edit(equipement cld )
        {
            NewdbEntities18 db = new NewdbEntities18();
            db.Entry(cld).State = EntityState.Modified;
            
            db.SaveChanges();
            return RedirectToAction("gestequip");

            //if (ModelState.IsValid)
            //{
            //    try
            //    {
            //        List<maintdetails> maintD = new List<maintdetails>();
            //        maintdetails ab = new maintdetails();
            //        ab.Numéro = mn.Numéro;
            //        ab.Département = mn.Département;
            //        ab.Référence = mn.Référence;
            //        ab.Libellé = mn.Libellé;
            //        ab.Type = mn.Type;
            //        maintD.Add(ab);
            //        //db.Entry(mn).State = EntityState.Modified;
            //        db.SaveChanges();
            //        return RedirectToAction("gestequip");
            //    }
            //    catch (Exception)
            //    {
            //        return RedirectToAction("Index");
            //    }

            //}
            ////db.SaveChanges();
            //return RedirectToAction("gestequip");
            ////return View(eqi);
        }
        public ActionResult Delete(int? id)
        {
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            equipement a = db.equipement.Find(id);
            //if (a == null)
            //{
            //    return HttpNotFound();
            //}
            return View(a);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            NewdbEntities18 db = new NewdbEntities18();
            equipement qui = db.equipement.Find(id);

            var l = from b in db.equipement
                    where b.id_equip == id
                    select b.id_equip;

            //equipement p = db.equipement.Find(id);
 
            foreach (var i in l)
            {
                var le =
                    from c in db.demande
                    where c.id_equip == i /*(from b in db.equipement where b.id_dep == id select b.id_equip;)*/
                    select c.id_demande;
                var lee =
                    from d in db.fiche_tech
                    where d.id_equip == i
                    select d.id_fiche;

WebApplication5/Views/mainten/Ajou.cshtml
@model WebApplication5.Models.piece

@{
    ViewBag.Title = "Ajou";
    Layout = "~/Views/mainten/_Layoutmainte.cshtml";
}

<h2>Ajou</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>piece</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id_piece, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_piece, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_piece, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_inter, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_inter, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_inter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.libellep, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.libellep, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.libellep, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.valeur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.valeur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.valeur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "dempiec")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication5/Views/mainten/Ajout.cshtml
@model WebApplication5.Models.class2

@{
    ViewBag.Title = "Ajout";
    Layout = "~/Views/mainten/_Layoutmainte.cshtml";
}

<h2>Ajout</h2>


@using (Html.BeginForm("Ajout", "mainten", FormMethod.Post))
{
    @Html.TextBoxFor(x => x.id_equip, new { @class = "form-control", @placeholder = "Numéro" })
    @Html.TextBoxFor(x => x.id_dep, new { @class = "form-control", @placeholder = "id depa" })
    @Html.TextBoxFor(x => x.libelledep, new { @class = "form-control", @placeholder = "Département" })
    @Html.TextBoxFor(x => x.@ref, new { @class = "form-control", @placeholder = "Référence" })
    @Html.TextBoxFor(x => x.libelleq, new { @class = "form-control", @placeholder = "Libelle" })
    @Html.TextBoxFor(x => x.id_type, new { @class = "form-control", @placeholder = "id type" })
    @Html.TextBoxFor(x => x.etat, new { @class = "form-control", @placeholder = "etat" })
    @Html.TextBoxFor(x => x.denomination, new { @class = "form-control", @placeholder = "Type" })
    @Html.TextBoxFor(x => x.id_fiche, new { @class = "form-control", @placeholder = "Fiche technique" })
    @Html.TextBoxFor(x => x.id_typentr, new { @class = "form-control", @placeholder = "id type entretien" })

    @Html.TextBoxFor(x => x.libellentr, new { @class = "form-control", @placeholder = "Historique de reparation" })
    <input type="submit" value="submit" class="btn btn-block btn-danger" />
    <br />

    <div>
        <br />
        @Html.ActionLink("Back ", "gestequip")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
}

WebApplication5/Views/mainten/Edit.cshtml
@model WebApplication5.Models.class2

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/mainten/_Layoutmainte.cshtml";
}
<style>
    h2 {
        color: #0026ff;
        text-decoration:solid;
        
    }
    input[type=submit] {
        background-color: #1478c4;
        border: none;
        color: white;
        padding: 16px 81px;
        text-decoration: none;
        
    }
    .div{position:center;}
</style>
<h2>Edit</h2>

@using (Html.BeginForm("Edit", "mainten", FormMethod.Post))
{<div>
    @Html.TextBoxFor(x => x.id_equip, new { @class = "form-control", @placeholder = "Numéro" })
    @Html.TextBoxFor(x => x.id_dep, new { @class = "form-control", @placeholder = "id depa" })
    @Html.TextBoxFor(x => x.libelledep, new { @class = "form-control", @placeholder = "Département" })
    @Html.TextBoxFor(x => x.@ref, new { @class = "form-control", @placeholder = "Référence" })
    @Html.TextBoxFor(x => x.libelleq, new { @class = "form-control", @placeholder = "Libelle" })
    @Html.TextBoxFor(x => x.id_type, new { @class = "form-control", @placeholder = "id type" })
    @Html.TextBoxFor(x => x.etat, new { @class = "form-control", @placeholder = "etat" })
    @Html.TextBoxFor(x => x.denomination, new { @class = "form-control", @placeholder = "Type" })
    @Html.TextBoxFor(x => x.id_fiche, new { @class = "form-control", @placeholder = "Fiche technique" })
    @Html.TextBoxFor(x => x.id_typentr, new { @class = "form-control", @placeholder = "id type entretien" })

    @Html.TextBoxFor(x => x.libellentr, new { @class = "form-control", @placeholder = "Historique de reparation" })
    <br />

    <input type="submit" value="submit" />
</div>
    @*@using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>class2</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.id_equip, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.id_equip, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.id_equip, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.@ref, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.@ref, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.@ref, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.libelledep, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.libelledep, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.libelledep, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.id_dep, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.id_dep, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.id_dep, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.id_type, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.id_type, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.id_type, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.denomination, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.denomination, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.denomination, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.etat, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.etat, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.etat, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.libelleq, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.libelleq, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.libelleq, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.id_fiche, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.id_fiche, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.id_fiche, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.id_typentr, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.id_typentr, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.id_typentr, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.libellentr, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.libellentr, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.libellentr, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>*@
}
<br/>
<br/>
<br/>


<div>
    @Html.ActionLink("Back", "gestequip")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication5/Views/mainten/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/mainten/_Layoutmainte.cshtml";
}
<br />
<br />
<h2>Bienvenue @Session["login"]</h2>

WebApplication5/Views/mainten/UploadFile.cshtml
@{
    ViewBag.Title = "UploadFile";
    Layout = "~/Views/mainten/_Layoutmainte.cshtml";
}

<h2>UploadFile</h2>
 
@using (Html.BeginForm("UploadFile", "mainten", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
        @Html.TextBox("file", "", new { type = "file" }) <br />
        <input type="submit" value="Upload" />
        @ViewBag.Message
    </div>
}

WebApplication5/Views/mainten/_Layoutmainte.cshtml
@*<!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
    </head>
    <body>
        <div>
            @RenderBody()
        </div>
    </body>
    </html>*@
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/Usertemp/css/style.css" type="text/css" media="all" />
    <link href="~/Content/fontawesome.css" rel="stylesheet" />
    <link href="~/Content/all.css" rel="stylesheet" />
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<style>
            navbar-collapse.collaps .nav.navbar-nav li:hover {
                background-color: #ddd;
                color: red;
            }
        </style>*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Home", "Registration", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href=""></a></li>
                    <li>@Html.ActionLink("gestion des equipement", "gestequip", "mainten")</li>
                    <li>@Html.ActionLink("gestion des réparations", "Index", "type_entretien")</li>
                    <li>@Html.ActionLink("demande de pieces", "dempiec", "mainten")</li>
                    <li>@Html.ActionLink("gestion des départements", "Homee", "departements")</li>

                    <li>@Html.ActionLink("gestion des types d'équipements", "Index", "types")</li>
                    @*<li>@Html.ActionLink("statistiques", "stat", "mainten")</li>*@
                    @*<li>@Html.ActionLink("Edit", "Edit", "mainten")</li>*@

                    @*<li>@Html.ActionLink("ajout demande", "Ajoudema", "Client")</li>
                        @*<li>@Html.ActionLink("Accueil", "Index", "Home")</li>
            <li>@Html.ActionLink("À propos de", "About", "Home")</li>
            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                <ul class=" topnav-right " style="float:right !important">
                    @if (Session["login"] != null)
                    {
                                 
                                <li><p style="color:#fff;margin-top:15px;">Hello @Session["login"]</p></li>
                                <li>@Html.ActionLink("Log Out", "LogOut", "User")</li>
                                                    }
                                                    else
                                                    {
                                <li>@Html.ActionLink("Sign up", "Registration", "User")</li>
                                <li>@Html.ActionLink("Sign in", "signin", "User")</li>
}

                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mon application ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication5/Views/mainten/dempiec.cshtml
@model IEnumerable<WebApplication5.Models.demdetails>


@{
    ViewBag.Title = "dempiec";
    Layout = "~/Views/mainten/_Layoutmainte.cshtml";
}
<br />
<br />
<br />
<h2>Demande des piéces</h2>
<style>
    .hi {
        padding: 8px;
    }
</style>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<table class="table table-bordered">
    <tr class="btn-primary">
        <th>
            Numéro
        </th>
        <th>
            Référence
        </th>
        <th>
            Libellé
        </th>
        <th>
            Type
        </th>
        <th>
            Piéces demandées
        </th>
        <th></th>
    </tr>

    @foreach (var item in ViewBag.Message)
    {
        <tr>
            <td>
                @item.Numéro)
            </td>
            <td>
                @item.Référence
            </td>
            <td>
                @item.Libellé
            </td>
            <td>
                @item.Type
            </td>
            <td>
                <div class="hi">
                    @Html.DropDownList("list", ViewBag.Pieces as SelectList, "Choix d'une piece")
                    <br />
                    <br />
                    @Html.ActionLink("Ajout", "Ajou", "mainten") |
                    @*<button class="btn btn-primary btn-sm" data-target="#loginModal" data-toggle="modal">Ajout</button>*@
                </div>
            </td>

        </tr>
    }

</table>

<!--<div class="container">
    <div class="row">
        <div class="col-xs-12">-->
@*<button class="btn btn-primary btn-sm" data-target="#loginModal" data-toggle="modal">bouton</button>*@
<!--<div class="modal fade" tabindex="-1" id="loginModal"
     data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    &times;
                </button>
                <h4 class="modal-title">demande de piéce</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">

                        <input class="form-control" placeholder="id_piéce"
                               type="text" id="inputUserName" />
                    </div>-->
@*<div class="form-group">

        <div class="hi">
            @Html.DropDownList("list", ViewBag.breakdown as SelectList, "please select one") <br />
        </div>
    </div>*@
<!--<div class="form-group">

    <input class="form-control" placeholder="nom de piéce"
           type="text" id="inputPanne" />
</div>
<div class="form-group">
    <input class="form-control" placeholder="Description"
           type="text" id="inputPanne" />-->
@*@Html.EditorFor(model=> Model.Where, new
    {
        htmlAttributes = new
        {
            @type = "text",
            @name = "w3lName",
            @id = "w3lName",
            @placeholder = "Description",
            @class = "contact-input",
            @required = ""
        }
    })*@
@*</div>
        </form>
    </div>
    <div class="modal-footer">*@
@*@Html.ActionLink("valider", "dempi", "mainten")*@
@*<button type="submit" class="btn btn-primary" Onclick="alert('votre demande est bien enregistrée')">Valider</button>*@
<!--<button type="button" class="btn btn-primary"
                                    data-dismiss="modal">
                                Close
                            </button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>-->