WebApplication5/Models/type_entretien.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_entretien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public type_entretien()
        {
            this.demande = new HashSet<demande>();
            this.intervention = new HashSet<intervention>();
        }
    
        public int id_typentr { get; set; }
        public string libellentr { get; set; }
        public string action_propose { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<demande> demande { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<intervention> intervention { get; set; }
    }
}

WebApplication5/Controllers/type_entretienController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using WebApplication5.Models;

namespace WebApplication5.Controllers
{
    public class type_entretienController : Controller
    {
        private NewdbEntities18 db = new NewdbEntities18();

        // GET: type_entretien
        public ActionResult Index()
        {
            NewdbEntities18 db = new NewdbEntities18();
            List<repdetails> maintD = new List<repdetails>();
            //clientdetails cd = new clientdetails();
            var num = db.equipement.Select(a => a.id_equip).ToList();
            var dept = db.departement.Select(a => a.libelledep).ToList();
            var rf = db.equipement.Select(a => a.@ref).ToList();
            var lb = db.equipement.Select(a => a.libelleq).ToList();
            var tp = db.type.Select(a => a.denomination).ToList();
            var inter = db.type_entretien.Select(a => a.libellentr).ToList();
            var mine = db.intervention.Select(a => a.nb_min).ToList();


            foreach (int item in num)
            {
                repdetails ab = new repdetails();
                ab.Numéro = item;
                ab.Département = dept[item - 1];
                ab.Référence = rf[item - 1];
                ab.Libellé = lb[item - 1];
                ab.Type = tp[item - 1];
                ab.intervention = inter[item - 1];
                if (mine[item - 1] != null)
                { ab.nombreheureinter = (int)mine[item - 1]; }
                else { ab.nombreheureinter = 0; }
                maintD.Add(ab);
            }
            ViewBag.Message = maintD;
            return View();
        }
        //    return View(db.type_entretien.ToList());
        //}

        public ActionResult SaveRecord(int? id)
        {
            intervention i = db.intervention.Find(id);
            return View(i);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveRecord([Bind(Include = "id_inter ,id_equip ,id_typenter, nb_min ,typenter , date_inter")] intervention intervention)
        {
            if (ModelState.IsValid)
            {
                db.Entry(intervention).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(intervention);
        }
        public ActionResult Ude(int? id)
        {
            intervention i = db.intervention.Find(id);
            return View();
        }
        [HttpPost]
        public ActionResult Ude(string gyp)
        {
            NewdbEntities18 db = new NewdbEntities18();
            if (gyp == "true")
            {
                DateTime dt = DateTime.Now;
                ViewBag.Message = "yupp";
                intervention inet = new intervention();
                inet.date_inter = dt;
                db.intervention.Add(inet);
                db.SaveChanges();

            }
            return RedirectToAction("Index");
        }
        //[HttpPost]
        //public ActionResult SaveRecord(repdetails model,int? id) {
        //    try
        //    {
        //        NewdbEntities15 db = new NewdbEntities15();
        //        intervention intt = new intervention();
        //        var inte = db.intervention.Select(a => a.id_inter).ToList();

        //        intervention i = new intervention();
        //        i=db.intervention.Find(id);
        //        //foreach (int item in inte)
        //        //{
        //        //var dbe = Database.Open("Newdb");
        //        //var inse = "INSERT INTO intervention(nb_min)"+" VALUES(model.nombreheureinter)";
        //        //dbe.Execute(inse, model.nombreheureinter);
        //        //repdetails ab = new repdetails();
        //        //if (item == ab.Numéro)
        //        //{
        //        //foreach (DataRow row in intervention.Rows)
        //        //{
        //        //    row["nb_min"] = model.nombreheureinter;
        //        //}
        //        i.nb_min = model.nombreheureinter;
        //        //intt.nb_min = model.nombreheureinter;

        //           db.intervention.Add(i);
        //           db.SaveChanges();
        //           //return RedirectToAction("Index");
        //    }
        //    catch(Exception ex) { throw ex; }
        //    return RedirectToAction("gestequip");
        //}

        // GET: type_entretien/Edit/5
        public ActionResult Edit(int? id)
        {
           
            type_entretien type_entretien = db.type_entretien.Find(id);
            
            return View(type_entretien);
        }
        
        // POST: type_entretien/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_typentr,libellentr,action_propose,description")] type_entretien type_entretien)
        {
            if (ModelState.IsValid)
            {
                db.Entry(type_entretien).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(type_entretien);
        }

       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication5/Views/type_entretien/Create.cshtml
@model WebApplication5.Models.type_entretien

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/mainten/_Layoutmainte.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>type_entretien</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id_typentr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_typentr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_typentr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.libellentr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.libellentr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.libellentr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.action_propose, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.action_propose, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.action_propose, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication5/Views/type_entretien/Delete.cshtml
@model WebApplication5.Models.type_entretien

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/mainten/_Layoutmainte.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>type_entretien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.libellentr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.libellentr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.action_propose)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.action_propose)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication5/Views/type_entretien/Details.cshtml
@model WebApplication5.Models.type_entretien

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/mainten/_Layoutmainte.cshtml";
}

<h2>Details</h2>

<div>
    <h4>type_entretien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.libellentr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.libellentr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.action_propose)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.action_propose)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_typentr }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication5/Views/type_entretien/Edit.cshtml
@model WebApplication5.Models.type_entretien

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/mainten/_Layoutmainte.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>type_entretien</h4>
    <hr />
    @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id_typentr)*@

    <div class="form-group">
        @Html.LabelFor(model => model.id_typentr, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.id_typentr, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.id_typentr, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.libellentr, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.libellentr, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.libellentr, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.action_propose, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.action_propose, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.action_propose, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication5/Views/type_entretien/Index.cshtml
@model WebApplication5.Models.repdetails

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/mainten/_Layoutmainte.cshtml";
}


<!Doctype html>
<html>
<head>
    <style>
        .container {
            display: block;
            position: relative;
            padding-left: 35px;
            margin-bottom: 12px;
            cursor: pointer;
            font-size: 14px;
        }

        /* Create a custom checkbox */
        .checkmark {
            position: absolute;
            top: 0;
            left: 0;
            height: 25px;
            width: 25px;
            background-color: #eee;
        }
        /* When the checkbox is checked, add a blue background */
        .container input:checked ~ .checkmark {
            background-color: #2196F3;
        }
        /* Create the checkmark/indicator (hidden when not checked) */
        .checkmark:after {
            content: "";
            position: absolute;
            display: none;
        }

        /* Show the checkmark when checked */
        .container input:checked ~ .checkmark:after {
            display: block;
        }

        /* Style the checkmark/indicator */
        .container .checkmark:after {
            left: 9px;
            top: 5px;
            width: 5px;
            height: 10px;
            border: solid white;
            border-width: 0 3px 3px 0;
            -webkit-transform: rotate(45deg);
            -ms-transform: rotate(45deg);
            transform: rotate(45deg);
        }
        .ok{
            width:30%;
        }
    </style>
</head>
<body>
    <br />
    <br />
    <br />
    <br />


    <h2>Gestion des réparations</h2>
    <br />
    @using (Html.BeginForm("SaveRecord", "type_entretien", FormMethod.Post))
    {

        @*<p>
                @Html.ActionLink("Create New", "Create")
            </p>*@
        <br />
        <table class="table table-bordered">
            <tr class="btn-primary">
                <th>
                    Numéro
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Département)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Référence)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Libellé)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Type)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.intervention)
                </th>
                <th>
                    Nombre d'heure d'intervention
                </th>
                <th>
                    Etat de l'intervention
                </th>
                <th></th>
            </tr>

            @foreach (var item in ViewBag.Message)
            {
        <tr>
            <td>
                @item.Numéro
            </td>
            <td>
                @item.Département
            </td>
            <td>
                @item.Référence
            </td>
            <td>
                @item.Libellé
            </td>
            <td>
                @item.Type
            </td>
            <td>

                <br />@item.intervention

                <li class="active"><a href="@Url.Action("Edit", "type_entretien")"><i class="fas fa-edit"></i> </a></li>
                @*@Html.ActionLink("Edit", "Edit", "type_entretien"*@@*new { id = item.id_dep }*@
                @*<button class="btn btn-primary btn-sm" data-target="#loginModal" data-toggle="modal">Modifier</button>*@
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.nombreheureinter)*@


                @*<input type="text" name="mn" id="mn"class="ok"/>*@
                @*<li class="active"><a href="@Url.Action("SaveRecord", "type_entretien")"><i class="fas fa-edit"></i> </a></li>*@
                @Html.ActionLink("Edit", "SaveRecord", "type_entretien"@*,new { id = item.Numéro }*@)
                <br />

                @*@Html.TextBoxFor(Model => Model.nombreheureinter, new { @class = "form-control" })*@
                @item.nombreheureinter <label> minutes</label>
            </td>
            @using (Html.BeginForm("Ude", "type_entretien", FormMethod.Post))
            {
                <td>
                    <div class="form-group">
                        <div classs="col-md-10">
                            <label class="checkbox-inline">
                                @Html.CheckBox("gyq", true)
                                <span class="checkmark"></span>
                                En attente
                            </label>
                        </div>
                        <div classs="col-md-10">
                            <label class="checkbox-inline">
                                @Html.CheckBox("gyp", false)
                                <span class="checkmark"></span>
                                Résolu
                            </label>
                        </div>

                    </div>
                
                    @*<label class="container">
                        En attente
                        <input type="checkbox" checked="checked">
                        <span class="checkmark"></span>
                    </label>


                            <label class="container">
                                Résolu
                                <input type="checkbox">
                                <span class="checkmark"></span>
                            </label>
                @if()*@
                </td>
                }
            </tr>
            }


        </table>
    }
</body>
</html>

WebApplication5/Views/type_entretien/SaveRecord.cshtml
@model WebApplication5.Models.intervention

@{
    ViewBag.Title = "SaveRecord";
    Layout = "~/Views/mainten/_Layoutmainte.cshtml";
}



<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>type_entretien</h4>
    <hr />
    @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_typentr)*@

    <div class="form-group">
        @Html.LabelFor(model => model.id_inter, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.id_inter, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.id_inter, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.id_equip, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.id_equip, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.id_equip, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.id_typenter, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.id_typenter, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.id_equip, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.nb_min, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nb_min, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nb_min, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.typenter, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.typenter, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.typenter, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.date_inter, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.date_inter, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.date_inter, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication5/Views/type_entretien/Ude.cshtml
@{
    ViewBag.Title = "Ude";


}
<style>
    .container {
        display: block;
        position: relative;
        padding-left: 35px;
        margin-bottom: 12px;
        cursor: pointer;
        font-size: 14px;
    }

    /* Create a custom checkbox */
    .checkmark {
        position: absolute;
        top: 0;
        left: 0;
        height: 25px;
        width: 25px;
        background-color: #eee;
    }
    /* When the checkbox is checked, add a blue background */
    .container input:checked ~ .checkmark {
        background-color: #2196F3;
    }
    /* Create the checkmark/indicator (hidden when not checked) */
    .checkmark:after {
        content: "";
        position: absolute;
        display: none;
    }

    /* Show the checkmark when checked */
    .container input:checked ~ .checkmark:after {
        display: block;
    }

    /* Style the checkmark/indicator */
    .container .checkmark:after {
        left: 9px;
        top: 5px;
        width: 5px;
        height: 10px;
        border: solid white;
        border-width: 0 3px 3px 0;
        -webkit-transform: rotate(45deg);
        -ms-transform: rotate(45deg);
        transform: rotate(45deg);
    }

    .ok {
        width: 30%;
    }
</style>
@*<h2>Ude</h2>
    @using (Html.BeginForm("Ude", "type_entretien", FormMethod.Post, new { @class = "form-horizontal" }))
    {<label class="container">
         <div class="form-group">
             <div classs="col-md-10">
                 <label class="checkbox-inline">
                     @Html.CheckBox("gyq", false)
                     <span class="checkmark"></span>
                     En attente
                 </label>
             </div>
             <div classs="col-md-10">
                 <label class="checkbox-inline">
                     @Html.CheckBox("gyp", false)
                     <span class="checkmark"></span>
                     Résolu
                 </label>
             </div>
             @ViewBag.Message
         </div>

     </label>}*@

<script>

    chxGrp.addEventListener('change', message);

    /* The Event Object is passed through, you might've seen it as
    || "e" or "evt". How it's labelled doesn't matter because Event
    || Object is always available when you deal with the DOM.
    */
    function message(event) {

        // if the node clicked is a checkbox see if it's...
        if (event.target.type === 'checkbox') {

            // ... checked then...
            if (event.target.checked) {

      // ...find the node that follows it (i.e. <b>
                event.target.nextElementSibling.className = "message";
            } else {
                /* Otherwise remove any class on it. (there's a more modern
                || method: classList that can be used instead)
                */
                event.target.nextElementSibling.className = "";
            }
        }
        return false;
    }
</script>
<style>
    b {
        display: none
    }

    label {
        display: table
    }

    [type=checkbox] {
        display: table-cell;
    }

    .message {
        display: table-cell;
    }
</style>
    <!DOCTYPE html>
    <html>

    <head>
    </head>

    <body>
        <!-- Wrapped the checkboxes with a <form> giving us opportunities:
        HTMLFormControlsCollection API for specialized referencing and
        Event Delegation allowing us to use a single eventListener for an
        unlimited amount of event.targets (clicked, changed, inputed,
        etc. buttons, links, etc.)-->
        <form id='checkGroup'>

            <p>Display some text when the checkbox is checked: </p>

            <label>
                Checkbox 1: <input type="checkbox">
                <b>Checkbox is CHECKED!</b>
            </label><br>

            <label>
                Checkbox 2: <input type="checkbox">
                <b>Second checkbox is checked</b>
            </label><br>

            <label>
                Checkbox 3: <input type="checkbox">
                <b>Third checkbox is checked</b>
            </label><br>

        </form>

    </body>

</html>